import canonicalLaneMathlib.AdmissibleClass
import HautevilleHouse.VariationalMethodsAppliedProblemsStatisticalCanonicalLaneLean.ExponentialFamily
import HautevilleHouse.VariationalMethodsAppliedProblemsStatisticalCanonicalLaneLean.NeymanPearsonLemma
import HautevilleHouse.VariationalMethodsAppliedProblemsStatisticalCanonicalLaneLean.MLE_Consistency

namespace HautevilleHouse
namespace VariationalMethodsAppliedProblemsStatisticalCanonicalLaneLean

def ConstrainedStatisticalClosure (A : AdmissibleClass) : Prop :=
  bridgeClosed A ∧ gateClosed A

theorem constrained_statistical_endgame (A : AdmissibleClass) : ConstrainedStatisticalClosure A := by
  exact And.intro (bridge_from_admissible_class A) (gate_from_admissible_class A)

end VariationalMethodsAppliedProblemsStatisticalCanonicalLaneLean
end HautevilleHouse